services:
  certui:
    container_name: certui
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - CERTUI_CONFIG_PATH=/config/config.yml
    volumes:
      - ./config:/config:ro
